name: Plugin Release

on:
  push:
    tags: ['plugin-v*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d30bece4fae2869c2 # v4

      - name: Publish plugin
        working-directory: intellij-plugin
        env:
          CERTIFICATE_CHAIN: ${{ secrets.PLUGIN_CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PLUGIN_PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PLUGIN_PRIVATE_KEY_PASSWORD }}
          PUBLISH_TOKEN: ${{ secrets.PLUGIN_PUBLISH_TOKEN }}
        run: ./gradlew signPlugin publishPlugin

      - name: Upload signed plugin
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: signed-plugin-zip
          path: intellij-plugin/build/distributions/*.zip
